ozamed/Python-Scripts

Desktop-App-Using-Tkinter/README.md
Desktop-App-Using-Tkinter/main.py

Hey, I have added a desktop application using Python. Tkinter is a standard GUI (Graphical User Interface) package of Python

Added Desktop application using Python

---

FizzBuzz/fizzbuzz.py

this program script is added in contribution to my friend ozamed

added fizzbuzz technique

---

google scrapper/google-scrapper.py

this script extracts data from a given page , by default it extracts the google home page data

added google scrapper script

---

Coin-Flip/coinflip.py

Added a simple Python script that recreates of flipping a coin.

Added coinflip.py

---

Match Stick Game/MatchStickGame.py

This Pull Request concerns with issue #1 
@ozamed Please review the code.

Added Match Stick Game

---

Rock-Paper Scissor.py

It's from my one of the liked notebooks. I have added it from my Jupyter Notebook.
It's easy to execute and is responsive.

Rock-Paper-Scissor Game

---

Rock-Paper-Scissor/Rock-Paper-Scissor.py

Previously the script was not in the folder i.e. added the script in the folder.
Thanks

Script is in the folder

---

Crypto with Key/crypto_key.py
Crypto with Key/secret.key
Crypto with Key/usage.txt

Added folder **"Crypto with Key"**.
**Usage:**
Execute "crypto_key.py" and choose an option:
-> 1 - **Generate** a new secret key
-> 2 - **Encrypt** a message
-> 3 - **Decrypt** a message
~ Cheers!

Added a new script folder

---

Fibonacci-Sequence/main.py

Hello!
I added a fibonacci sequence script inside **Fibonacci-Sequence** folder.
Hope it's a cool adding!
_saxocat_

Added fibonacci sequence script

---

Random-Wikipedia-Article/main.py

Hello!
I added a new script inside the **Random-Wikipedia-Article** folder!
I hope it's a cool adding!
_saxocat_

Added Random Wikipedia Article script!

---

UUIDv4-Generator/main.py

Hello!
I added a new script inside **UUIDv4-Generator** folder. Just like folder's name tells, the code creates UUIDv4.
Hope it's a cool adding!
_saxocat_

Added new script - UUIDv4 Generator

---

hangman/hangman.py

its a word guessing game
**Happy Hacktoberfest**

game hangman.py

---

README.md

Hi @ozamed , I apologise for not adding your name to the contributors list as I thought that since you own this Repo , it wouldn't be necessary but if you would like me to add you as well , let me know and I'll add you as soon as I can . Hope the file is better now . Cheers

Updated README with Contributors list

---

Dual_Song/README.md
Dual_Song/playduo.py

Play dual song at the same time. One song play in the left and another song play on the right side. I hope you like this feature very much.
Signed-off-by: mhdzumair <mhdzumair@gmail.com>

PlayDualSong:Implement play dual song script

---

Lorem-Picsum/main.py

Hello,
I have added a script, "Lorem Ipsum". It asks for the width of the image and the height of the image that it should fetch. It then uses the lorem picsum API to fetch and download a random image with those dimensions.

Lorem picsum

---

audiobook/README.md
audiobook/read_pdf.py

This is the awesome CLI Simple Audiobook,
Signed-off-by: mhdzumair <mhdzumair@gmail.com>

audiobook: Impliment simple CLI audiobook

---

Remove-Duplicate-Images/remove_duplicates.py

This script is used to Remove duplicate images from a folder/directory

Remove duplicate images

---

README.md
Youtube_Downloader/README.md
Youtube_Downloader/youtube.py

Implement Youtube CLI Downloader & update README

YouTube_Downloader: Implement CLI YouTube Playlist/Video Downloader

---

README.md

Profile icons added along with the name

profile icons added

---

Resume-Parser/Resume-Parser.py

Hello!
I just created a script to parse resume and extract the most relevant data (email , full name , university ,dates , phone Number , inkedin or Github links) make cleaning with nltk 
#Hackoctoberfest
Rebai Ahmed

Added Script Resume-Parser

---

Fetch old Tweets/main.py
README.md

Fetch old Tweets via python script.

Fetch old Tweets via python script

---

Pong Game/main.py
Pong Game/pong.kv

Added a new project. (Pong Game)

Pong Game added

---

Music Player/MusicPlayer.py
Music Player/README.md

This project is a basic music player.
It plays the song available in that folder using 'Select Songs' button and 'o' button is used to start or stop the song.
Note : The songs playlist should be in the same folder as the code.

Added Music Player Script
